export const ToolNames = {
    USER_INFO: 'user-info',
    FETCH_INBOX: 'fetch-inbox',
    LOAD_THREAD: 'load-thread',
    LOAD_CONVERSATION: 'load-conversation',
    SEARCH_CONTENT: 'search-content',
    CREATE_THREAD: 'create-thread',
    UPDATE_THREAD: 'update-thread',
    UPDATE_COMMENT: 'update-comment',
    REPLY: 'reply',
    REACT: 'react',
    MARK_DONE: 'mark-done',
    BUILD_LINK: 'build-link',
    GET_WORKSPACES: 'get-workspaces',
    GET_USERS: 'get-users',
    AWAY: 'away',
    LIST_CHANNELS: 'list-channels',
} as const
