export const ToolNames = {
    USER_INFO: 'user-info',
    FETCH_INBOX: 'fetch-inbox',
    LOAD_THREAD: 'load-thread',
    LOAD_CONVERSATION: 'load-conversation',
    SEARCH_CONTENT: 'search-content',
    GET_MENTIONS: 'get-mentions',
    CREATE_THREAD: 'create-thread',
    CREATE_CONVERSATION: 'create-conversation',
    UPDATE_OBJECT: 'update-object',
    DELETE_OBJECT: 'delete-object',
    REPLY: 'reply',
    REACT: 'react',
    MARK_DONE: 'mark-done',
    BUILD_LINK: 'build-link',
    GET_WORKSPACES: 'get-workspaces',
    GET_USERS: 'get-users',
    GET_GROUPS: 'get-groups',
    AWAY: 'away',
    LIST_CHANNELS: 'list-channels',
} as const
